repos:
- hooks:
  - args:
    - --py310-plus
    id: pyupgrade
  repo: https://github.com/asottile/pyupgrade
  rev: v2.32.0
- hooks:
  - args:
    - --settings-path
    - pyproject.toml
    - --profile
    - black
    - --filter-files
    - --magic-placement
    - -b
    id: isort
  repo: https://github.com/pycqa/isort
  rev: 5.5.2
- hooks:
  - id: black
    language_version: python3
    args:
    - --preview
  repo: https://github.com/ambv/black
  rev: 22.3.0
- hooks:
  - additional_dependencies:
    - flake8-blind-except
    - flake8-bandit
    - flake8-comprehensions
    - flake8-mutable
    - flake8-bugbear
    id: flake8
  repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
- hooks:
  - additional_dependencies:
    - black==22.3.0
    id: blacken-docs
  repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
- hooks:
  - args:
    - --in-place
    id: docformatter
  repo: https://github.com/myint/docformatter
  rev: v1.4
- hooks:
  - args:
    - --skip=poetry.lock,front/*,deployment/*,README.md
    - --builtin=clear
    id: codespell
  repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: 'v1.6.0'
  hooks:
   -   id: autopep8
- repo: https://github.com/hadialqattan/pycln
  rev: v1.3.1
  hooks:
    - id: pycln
      args: [--config=pyproject.toml]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.950'
    hooks:
    -   id: mypy
        args:
          - --config-file
          - pyproject.toml
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        files: "\\.(py|txt|yaml|json|md|toml|lock|cfg|html|sh|js|yml)$"
      - id: trailing-whitespace
        files: "\\.(py|txt|yaml|json|md|toml|lock|cfg|html|sh|js|yml)$"
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-byte-order-marker
      - id: check-added-large-files
      - id: check-executables-have-shebangs
